In [2]:
import numpy as np

### array创建数组

numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

In [3]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([[1,2,3,4],[5,6,7,8]])
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
a,b,c

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [4]:
np.array([1,2,3,4,5,6,7,8,9], ndmin = 2)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

### arrange创建数组

numpy.arange(start, stop, step, dtype)

In [6]:
a = np.arange(10)
b = np.arange(0, 10, 2)
c = np.arange(0, 1, 0.1, dtype=float)
a,b,c

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 2, 4, 6, 8]),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]))

In [13]:
np.array([np.arange(4),np.arange(4,8)])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### 随机数数组
##### 随机数
numpy.random.random(size)

##### 随机种子(固定随机数)
np.random.seed(0)

##### 随机整数(随机整数)
np.random.randint(low, high, size)

##### 正态分布 (期望0 方差1)
np.random.randn(1)
np.random.normal(loc = 3, scale = 4, size = (2,3)) loc期望 scale方差

In [54]:
np.random.seed(0)
np.random.random((2,5,4))
np.random.randint(0, 100, size = 1)
np.random.randn(10)
np.random.normal(5,5,(2,3))

array([[ 5.57479586,  6.72656321, -3.67479382],
       [13.29175553, 16.49885762,  2.6443237 ]])