In [1]:
import torch

In [16]:
x = torch.arange(4.0)
x.requires_grad = True
y = 2 * torch.dot(x, x)
y.backward()
print(x.grad)

tensor([ 0.,  4.,  8., 12.])


In [17]:
# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [21]:
x.grad.zero_()
y = x * x
#若目标张量 y 是向量、矩阵等多维结构，必须通过 gradient 参数指定每个元素的梯度权重，以定义反向传播的初始梯度方向
y.backward(torch.ones_like(x))
x.grad

tensor([0., 2., 4., 6.])

In [24]:
x.grad.zero_()
y = x * x
u = y.detach() #当做一个常量计算
z = u * x
z.backward(torch.ones_like(x))
print(x.grad)

tensor([0., 1., 4., 9.])
