In [1]:
import torch
from torch import nn
from torch.nn import functional as F

x = torch.arange(4)
torch.save(x, 'x-file')

In [2]:
x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

In [3]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

In [5]:
Y

tensor([[-0.1978, -0.1543,  0.0081,  0.1285,  0.1354,  0.3291,  0.0930,  0.0247,
         -0.2406,  0.0166],
        [-0.1890, -0.0433,  0.2371,  0.5671,  0.3641,  0.1684,  0.1661, -0.2471,
         -0.0953,  0.4477]], grad_fn=<AddmmBackward0>)

In [6]:
net.state_dict()

OrderedDict([('hidden.weight',
              tensor([[ 0.1730,  0.1261,  0.1577,  ..., -0.1392,  0.0356,  0.1602],
                      [-0.0726, -0.1569, -0.1300,  ..., -0.1203, -0.0509,  0.0702],
                      [-0.0092, -0.0548, -0.2093,  ...,  0.0854, -0.1478, -0.2126],
                      ...,
                      [-0.0117, -0.0150,  0.1428,  ..., -0.1404, -0.0253,  0.1941],
                      [-0.0795, -0.1638,  0.1272,  ..., -0.1344,  0.1499, -0.0988],
                      [ 0.0786, -0.0167, -0.1046,  ..., -0.2208,  0.1561, -0.0953]])),
             ('hidden.bias',
              tensor([-0.0927, -0.0066,  0.1758,  0.2169, -0.0803, -0.1042, -0.0713, -0.2010,
                      -0.1585,  0.0513, -0.0112, -0.1520,  0.1752, -0.0740, -0.0969,  0.1664,
                      -0.2083,  0.2235, -0.1226, -0.0374, -0.2110, -0.0688,  0.0280, -0.0392,
                       0.0833, -0.0092,  0.1572, -0.2207, -0.0193, -0.0318, -0.1539,  0.2158,
                      -0.1814,

In [7]:
torch.save(net.state_dict(), 'mlp.params')

In [9]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)